title: Contadoria
url: "https://contadoria.github.io"
baseurl:

collections:
  projects:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - 
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      _options:
        image_path:
          width: 2000
          height: 2000
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS